package error

sealed trait AppError

case object UpdateUnsuccessfulProjectDoesNotExist extends AppError
case object DeleteUnsuccessfulProjectDoesNotExist extends AppError
case object CannotLogNewTaskWithTheOverlappingTimeRangeForTheSameUser extends AppError
case object CannotLogNewTaskWithDuplicateTaskDescriptionUnderTheSameProject extends AppError
case object UserNotFound extends AppError
case object CannotChangeNameGivenProjectNameExistsAlready extends AppError
case object ProjectNotCreated extends AppError
case object CannotCreateUserWithGeneratedUUID extends AppError
case object DeleteProjectUnsuccessful extends AppError
case object FetchingTaskForProjectUnsuccessful extends AppError
case object CouldNotFindTheTask extends AppError
case object CannotChangeNameGivenTaskExistsAlready extends AppError
case object FetchingTaskUnsuccessful extends AppError
case object TaskUpdateUnsuccessful extends AppError
case object TaskWithGivenNameDoesNotExist extends AppError